#!/usr/bin/env python

import sys, os

app_dir = os.path.dirname(__file__)

sys.path.insert(0, app_dir)
sys.path.insert(0, os.path.join(app_dir, 'rox-lib', 'ROX-Lib2', 'python'))

import rox, pager
from pager import Pager

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

pager = Pager(sys.argv[1])
rox.mainloop()

