#!/usr/bin/env python3

import os
import sys

app_dir = os.path.dirname(__file__)

sys.path.insert(0, app_dir)
sys.path.insert(0, os.path.join(app_dir, 'rox-lib', 'ROX-Lib3', 'python'))

import rox
from pager import PagerApplet

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

pager = PagerApplet(sys.argv[1])
rox.mainloop()
